name: Paul Truesdell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75501
title: Paul Truesdell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192938'
    - '#b7b9b8'
    - '#4e98b1'
    - '#157ca4'
    - '#887571'
  brandStrength: 0.8731878863181919
  lightness: 0.6766558322124183
  saturation: 0.2577706330921501
  rhythmicContrast: 0.7201846037060022
purpose: []
